// <auto-generated />
namespace EFCardinalityDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class product_image_update2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_image_update2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261711529_product_image_update2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
